#:schema node_modules/wrangler/config-schema.json
name = "logicard-duel-server"
main = "src/index.ts"
compatibility_date = "2024-12-30"

[observability]
enabled = true

[env.dev]
name = "logicard-duel-server-dev"

[env.dev.define]
ENVIRONMENT="dev"
UPSTASH_REDIS_REST_URL="http://localhost:6379"
UPSTASH_REDIS_REST_TOKEN=""
GOOGLE_CLIENT_ID="xxx"
GOOGLE_CLIENT_SECRET="xxx"
GOOGLE_REDIRECT_URI="http://localhost:5173"
JWT_SECRET="xxx"
JWT_EXPIRES_IN="1d"
APP_ROOT_EMAIL="admin@logicarduel.com"
APP_ROOT_PASSWORD="admin"

[[d1_databases]]
binding = "DB"
database_name = "logicard-duel-db"
database_id = "634c8fef-b30c-4f22-8d45-490122dd9d6c"

[env.production]
name = "logicard-duel-server"

[env.production.define]
ENVIRONMENT="production"


[[env.production.d1_databases]]
binding = "DB"
database_name = "logicard-duel-db"
database_id = "634c8fef-b30c-4f22-8d45-490122dd9d6c"